export const caseStudies = [
  {
    id: "builtwithdjango",
    name: "Built with Django",
    owner: "builtwithdjango",
    repo: "builtwithdjango",
    role: "Maintainer",
    description: "A public directory and community surface for real products built with Django.",
    language: "Django / HTML",
    repoUrl: "https://github.com/builtwithdjango/builtwithdjango",
    homepage: "https://builtwithdjango.com",
    stats: ["77 stars", "12 forks", "50 commits last year", "Community directory"],
    tags: ["Django", "community", "directory", "newsletter"],
    bullets: [
      "Turns an ecosystem into a useful discovery product with submissions, editorial curation, and project pages.",
      "Recent work touched modernization, blog APIs, newsletter customization, and home-page product flows.",
      "A credible Django signal because it is both a real web app and a public community asset.",
    ],
    accent: "green",
  },
  {
    id: "tuxseo",
    name: "TuxSEO",
    owner: "rasulkireev",
    repo: "TuxSEO",
    role: "Creator",
    description: "AI-assisted content generation and SEO workflow automation for founders.",
    language: "Python",
    repoUrl: "https://github.com/rasulkireev/TuxSEO",
    homepage: "https://tuxseo.com",
    stats: ["58 stars", "9 forks", "449 commits last year", "100 PRs last year"],
    tags: ["AI", "Django", "agents", "content automation"],
    bullets: [
      "End-to-end product work across prompts, backend jobs, publishing flows, product copy, and deployment.",
      "Recent work includes agent instruction consolidation, content generation revamps, and API/provider hardening.",
      "Relevant to applied AI teams because it sits where model behavior, user workflows, and product polish meet.",
    ],
    accent: "red",
  },
  {
    id: "tjalerts",
    name: "TJ Alerts",
    owner: "rasulkireev",
    repo: "tjalerts",
    role: "Creator",
    description: "Alerting and content automation system with digest, indexing, and AI-assisted workflows.",
    language: "Python",
    repoUrl: "https://github.com/rasulkireev/tjalerts",
    homepage: "",
    stats: ["Python", "44 PRs", "Recent AI model updates", "Automated blog submission"],
    tags: ["Django", "alerts", "digests", "automation"],
    bullets: [
      "Long-running product codebase with indexing, custom filters, similar-post discovery, and daily digest work.",
      "Recent PRs fixed company email indexing, updated OpenAI defaults, and modernized the app.",
      "Shows maintenance judgment: useful systems are revisited, refactored, and kept compatible with changing APIs.",
    ],
    accent: "blue",
  },
];

export const featuredProjects = [
  {
    name: "django-saas-starter",
    owner: "LVTD-LLC",
    repo: "django-saas-starter",
    role: "Maintainer",
    description: "Django cookiecutter for starting SaaS projects quickly.",
    language: "Python",
    stars: 23,
    forks: 2,
    homepage: "https://lvtd-llc.github.io/django-saas-starter/",
    repoUrl: "https://github.com/LVTD-LLC/django-saas-starter",
    tags: ["Django", "Hotwire", "deployment", "templates"],
    proof: "Recent merged work spans OAuth, Docker, Fly.io, frontend simplification, and AI dev guidance.",
  },
  {
    name: "Paperclip",
    owner: "gregagi",
    repo: "paperclip",
    role: "Contributor",
    description: "Open-source orchestration for zero-human companies.",
    language: "TypeScript",
    stars: 0,
    forks: 0,
    homepage: "https://paperclip.ing",
    repoUrl: "https://github.com/gregagi/paperclip",
    tags: ["AI agents", "orchestration", "React", "Node"],
    proof: "A relevant AI systems UI: org charts, budgets, heartbeats, governance, and agent coordination.",
  },
  {
    name: "FileBridge",
    owner: "LVTD-LLC",
    repo: "filebridge",
    role: "Creator",
    description: "Turn uploaded files into clean API endpoints and structured data feeds.",
    language: "Python",
    stars: 0,
    forks: 0,
    homepage: "",
    repoUrl: "https://github.com/LVTD-LLC/filebridge",
    tags: ["Django", "API", "MCP", "Google Sheets"],
    proof: "Recent work added MCP dataset row tools, Google Sheets write-back sync, OAuth, and UI polish.",
  },
  {
    name: "TalentLeads",
    owner: "rasulkireev",
    repo: "talentleads",
    role: "Creator",
    description: "Lead generation and outreach product experiments with automation and vector search.",
    language: "HTML",
    stars: 0,
    forks: 0,
    homepage: "",
    repoUrl: "https://github.com/rasulkireev/talentleads",
    tags: ["Django", "vectors", "automation", "observability"],
    proof: "Recent PRs include vectors, modernization, blog work, OpenTelemetry, and automated marketing emails.",
  },
  {
    name: "OSIG",
    owner: "rasulkireev",
    repo: "osig",
    role: "Creator",
    description: "Generate beautiful Open Graph images for your site.",
    language: "Python",
    stars: 2,
    forks: 0,
    homepage: "https://osig.app",
    repoUrl: "https://github.com/rasulkireev/osig",
    tags: ["Python", "images", "publishing", "open-source"],
    proof: "Recent work added publishing endpoints, observability, filtering, and blog link polish.",
  },
  {
    name: "awesome-basb",
    owner: "rasulkireev",
    repo: "awesome-basb",
    role: "Curator",
    description: "A curated list of resources for Building a Second Brain.",
    language: "Markdown",
    stars: 98,
    forks: 12,
    homepage: "https://rasulkireev.github.io/awesome-basb/",
    repoUrl: "https://github.com/rasulkireev/awesome-basb",
    tags: ["awesome-list", "knowledge", "community", "curation"],
    proof: "A durable open-source curation project with the largest star count in the portfolio.",
  },
];

export const contributions = [
  {
    title: "Simplified generated frontend stack",
    project: "LVTD-LLC/django-saas-starter",
    url: "https://github.com/LVTD-LLC/django-saas-starter/pull/79",
    meta: "Merged May 21, 2026",
  },
  {
    title: "Added Fly.io deployment support",
    project: "LVTD-LLC/django-saas-starter",
    url: "https://github.com/LVTD-LLC/django-saas-starter/pull/78",
    meta: "Merged May 21, 2026",
  },
  {
    title: "Added MCP dataset row management tools",
    project: "LVTD-LLC/filebridge",
    url: "https://github.com/LVTD-LLC/filebridge/pull/32",
    meta: "Merged May 15, 2026",
  },
  {
    title: "Added Google Sheets write-back sync",
    project: "LVTD-LLC/filebridge",
    url: "https://github.com/LVTD-LLC/filebridge/pull/33",
    meta: "Merged May 15, 2026",
  },
  {
    title: "Polished Google Sheets connection UI",
    project: "LVTD-LLC/filebridge",
    url: "https://github.com/LVTD-LLC/filebridge/pull/39",
    meta: "Merged May 16, 2026",
  },
  {
    title: "Consolidated agent instructions",
    project: "rasulkireev/TuxSEO",
    url: "https://github.com/rasulkireev/TuxSEO/pull/250",
    meta: "Merged May 20, 2026",
  },
  {
    title: "Fixed oversized company email index",
    project: "rasulkireev/tjalerts",
    url: "https://github.com/rasulkireev/tjalerts/pull/44",
    meta: "Merged May 11, 2026",
  },
  {
    title: "Added vector workflow",
    project: "rasulkireev/talentleads",
    url: "https://github.com/rasulkireev/talentleads/pull/17",
    meta: "Merged Oct 18, 2025",
  },
  {
    title: "Modernized TJ Alerts",
    project: "rasulkireev/tjalerts",
    url: "https://github.com/rasulkireev/tjalerts/pull/42",
    meta: "Merged Oct 24, 2025",
  },
];

export const archiveProjects = [
  ["ask-hn-digests", "Digest of engaging Hacker News discussions.", "92 commits last year", "https://github.com/rasulkireev/ask-hn-digests"],
  ["cleanapp", "Anki for your sites.", "28 commits last year", "https://github.com/rasulkireev/cleanapp"],
  ["gregagi/awesome-django", "Curated Django ecosystem resource with a live site.", "Django ecosystem", "https://github.com/gregagi/awesome-django"],
  ["LVTD-LLC/mac-apps-directory", "Searchable Astro directory for open-source macOS apps.", "Astro", "https://github.com/LVTD-LLC/mac-apps-directory"],
  ["LVTD-LLC/colorpick", "Open-source macOS color picker utility built with SwiftUI.", "Swift", "https://github.com/LVTD-LLC/colorpick"],
  ["LVTD-LLC/paperclip-openclaw-bridge", "Third-party Paperclip adapter for OpenClaw Gateway.", "TypeScript", "https://github.com/LVTD-LLC/paperclip-openclaw-bridge"],
  ["awesome-selfhosted-analysis", "Analysis of Awesome Self-Hosted repositories.", "JavaScript", "https://github.com/rasulkireev/awesome-selfhosted-analysis"],
  ["joplin-plugin-better-markdown-exporter", "Markdown exporter plugin for Joplin.", "TypeScript", "https://github.com/rasulkireev/joplin-plugin-better-markdown-exporter"],
  ["auto-tags-obsidian", "Obsidian plugin that generates note tags.", "TypeScript", "https://github.com/rasulkireev/auto-tags-obsidian"],
  ["knowthyself", "Personal data aggregation and reflection project.", "Python", "https://github.com/rasulkireev/knowthyself"],
];
