export const featuredProjects = [
  {
    name: "TuxSEO",
    owner: "rasulkireev",
    repo: "TuxSEO",
    role: "Creator",
    description: "Automated blog content creation for founders who hate writing.",
    language: "Python",
    stars: 58,
    forks: 9,
    homepage: "https://tuxseo.com",
    repoUrl: "https://github.com/rasulkireev/TuxSEO",
    tags: ["AI", "Django", "agents", "content"],
    proof: "449 commits and 100 PR contributions in the last year.",
  },
  {
    name: "django-saas-starter",
    owner: "LVTD-LLC",
    repo: "django-saas-starter",
    role: "Maintainer",
    description: "Django cookiecutter for starting SaaS projects quickly.",
    language: "Python",
    stars: 23,
    forks: 2,
    homepage: "https://lvtd-llc.github.io/django-saas-starter/",
    repoUrl: "https://github.com/LVTD-LLC/django-saas-starter",
    tags: ["Django", "Hotwire", "deployment", "templates"],
    proof: "Recent merged work spans OAuth, Docker, Fly.io, frontend simplification, and AI dev guidance.",
  },
  {
    name: "builtwithdjango",
    owner: "builtwithdjango",
    repo: "builtwithdjango",
    role: "Maintainer",
    description: "A web app highlighting real projects built with Django.",
    language: "HTML",
    stars: 77,
    forks: 12,
    homepage: "https://builtwithdjango.com",
    repoUrl: "https://github.com/builtwithdjango/builtwithdjango",
    tags: ["Django", "community", "directory", "product"],
    proof: "50 commits and recent PRs across modernization, API, newsletter, and product surfaces.",
  },
  {
    name: "obsidian-readwise",
    owner: "readwiseio",
    repo: "obsidian-readwise",
    role: "Contributor",
    description: "Official Readwise plugin for Obsidian.",
    language: "TypeScript",
    stars: 342,
    forks: 27,
    homepage: "",
    repoUrl: "https://github.com/readwiseio/obsidian-readwise",
    tags: ["TypeScript", "Obsidian", "docs", "CI"],
    proof: "Recent merged work added plugin publishing guidance, CI workflow, and expired account handling.",
  },
  {
    name: "OSIG",
    owner: "rasulkireev",
    repo: "osig",
    role: "Creator",
    description: "Generate beautiful Open Graph images for your site.",
    language: "Python",
    stars: 2,
    forks: 0,
    homepage: "https://osig.app",
    repoUrl: "https://github.com/rasulkireev/osig",
    tags: ["Python", "images", "publishing", "open-source"],
    proof: "Recent work added publishing endpoints, observability, filtering, and blog link polish.",
  },
  {
    name: "Math MCP",
    owner: "rasulkireev",
    repo: "math-mcp",
    role: "Creator",
    description: "MCP server with various math operations.",
    language: "Python",
    stars: 0,
    forks: 0,
    homepage: "https://math-mcp.rasulkireev.com/mcp",
    repoUrl: "https://github.com/rasulkireev/math-mcp",
    tags: ["MCP", "Python", "tools", "API"],
    proof: "A focused protocol experiment with hosted endpoint and logging iteration.",
  },
];

export const contributions = [
  {
    title: "Simplified generated frontend stack",
    project: "LVTD-LLC/django-saas-starter",
    url: "https://github.com/LVTD-LLC/django-saas-starter/pull/79",
    meta: "Merged May 21, 2026",
  },
  {
    title: "Added Fly.io deployment support",
    project: "LVTD-LLC/django-saas-starter",
    url: "https://github.com/LVTD-LLC/django-saas-starter/pull/78",
    meta: "Merged May 21, 2026",
  },
  {
    title: "Added OAuth auth to MCP starter flow",
    project: "LVTD-LLC/django-saas-starter",
    url: "https://github.com/LVTD-LLC/django-saas-starter/pull/76",
    meta: "Merged May 20, 2026",
  },
  {
    title: "Improved Obsidian screen capture and packaging",
    project: "LVTD-LLC/colorpick",
    url: "https://github.com/LVTD-LLC/colorpick/pull/2",
    meta: "Merged May 19, 2026",
  },
  {
    title: "Consolidated agent instructions",
    project: "rasulkireev/TuxSEO",
    url: "https://github.com/rasulkireev/TuxSEO/pull/250",
    meta: "Merged May 20, 2026",
  },
  {
    title: "Added Readwise Obsidian plugin publishing guide",
    project: "readwiseio/obsidian-readwise",
    url: "https://github.com/readwiseio/obsidian-readwise/pull/96",
    meta: "Merged May 14, 2026",
  },
  {
    title: "Added Readwise Obsidian testing workflow",
    project: "readwiseio/obsidian-readwise",
    url: "https://github.com/readwiseio/obsidian-readwise/pull/95",
    meta: "Merged May 14, 2026",
  },
  {
    title: "Handled expired account errors",
    project: "readwiseio/obsidian-readwise",
    url: "https://github.com/readwiseio/obsidian-readwise/pull/94",
    meta: "Merged May 14, 2026",
  },
];

export const archiveProjects = [
  ["awesome-basb", "Curated Building a Second Brain resources.", "98 stars", "https://github.com/rasulkireev/awesome-basb"],
  ["ask-hn-digests", "Digest of engaging Hacker News discussions.", "92 commits last year", "https://github.com/rasulkireev/ask-hn-digests"],
  ["cleanapp", "Anki for your sites.", "28 commits last year", "https://github.com/rasulkireev/cleanapp"],
  ["awesome-selfhosted-analysis", "Analysis of Awesome Self-Hosted repositories.", "JavaScript", "https://github.com/rasulkireev/awesome-selfhosted-analysis"],
  ["joplin-plugin-better-markdown-exporter", "Markdown exporter plugin for Joplin.", "TypeScript", "https://github.com/rasulkireev/joplin-plugin-better-markdown-exporter"],
  ["auto-tags-obsidian", "Obsidian plugin that generates note tags.", "TypeScript", "https://github.com/rasulkireev/auto-tags-obsidian"],
  ["knowthyself", "Personal data aggregation and reflection project.", "Python", "https://github.com/rasulkireev/knowthyself"],
  ["awesome-selfhosted-data", "Contribution to the machine-readable self-hosted catalog.", "Merged PR", "https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/1646"],
  ["dj-stripe", "Patch contribution to Django Stripe tooling.", "Open PR", "https://github.com/dj-stripe/dj-stripe/pull/2199"],
];
